### ISSUE TITLE
Parsing labels in skidl.py

### ISSUE THREAD

**Issue by sean5446** [adamws/kle2netlist#1]
## Issue

Firstly, thank you so much for making this. It's amazing. 
Forgive me if I am doing something incorrectly, my ultimate goal was to place a dip socket instead of the ATMEGA32U4AU. I have an STM32F411CEU6 board that I'd like to use to prototype a keyboard. 

I take the default KLE json of "keycool 84":
https://pastebin.com/AiS5TqFj

And convert it to "internal form":
https://pastebin.com/HfpJhNSw

I then run (I just grabbed the tar from the github workflow build.yml for the switch symbols):
`kle2netlist --layout keyboard-layout-converted.json --output-dir out --lib-path "/home/queso/src/kicad-symbols-v5"`

In `skidl.py`, line 197 I run into a problem on the split of `None`:
```python
        row, column = map(int, labels[0].split(","))
```

As you'll see in the internal form of the KLE json, the first element of `labels` is null in most cases:
```json
{
  "keys": [
    {
      "color": "#cccccc",
      "labels": [
        null,
        null,
        null,
        "Esc"
      ],
```

If I change the line to:
```python
        row, column = key['y'], key['x']
```

I _think_ that might solve the issue? but I'm not sure as I'm not very familiar with the internal representation. 

## Other notes:
Do you know why `.erc` and `.log` files are created every time I run a file in the project? 

I had to manually downgrade `MarkupSafe==2.0.1` to fix issue:
`ImportError: cannot import name 'soft_unicode' from 'markupsafe'`
I think the poetry.lock file could be updated. 
```
[package.dependencies]
MarkupSafe = ">=0.23"
```

**Comment by adamws** [comment]
Hi @sean5446
take a look on [this](https://adamws.github.io/keyboard-tools/kicad-project-generator/examples.html#annotated-keys) and [this](https://adamws.github.io/keyboard-tools/kicad-project-generator/examples.html#annotated-keys) - first label needs to have `row,column` format - this determines how keys are connected together. This is not the same as `x`/`y` values which represents position of a key. `kle2netlist` is currently not able to do automatic assignment of `row` and `column` to a key - this is an option in https://github.com/adamws/keyboard-tools which uses this project.

Here is my question about logging on skidl repository: https://github.com/devbisme/skidl/issues/102 - I didn't progress with this yet.

Dependencies issues are solved on https://github.com/adamws/kle2netlist/tree/develop
